config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :beers

  resources :breweries

  resources :memberships

  resources :beer_clubs

  resources :styles

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_frozen', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

  get 'ngbeerlist', to:'beers#nglist'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates :year, numericality: {greater_than_or_equal_to: 1042, less_than_or_equal_to: Proc.new {Date.today.year}}
  validates :name, presence: true

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  def print_report
    puts name
    puts "established at year #{year}"
    beers puts "number of beers #{beers.count}"
  end
  def restart
    self.year = 2015
    puts "changed year to #{self.year}"
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating||0) }
    sorted_by_rating_in_desc_order[0,n]
  end
  private

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :is_admin, only: [:destroy]

  before_action :skip_if_cached, only:[:index]

  # GET /breweries
  # GET /breweries.json


  def skip_if_cached
    @sort = params[:sort] || 'asc'
    if @sort == 'asc'
      @direction = 'desc'
    else
      @direction = 'asc'
    end
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}-#{@direction}"  )
  end

  def list

  end

  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all


    if @sort == 'asc'
      @active_breweries = case @order
                            when 'name' then @active_breweries.sort_by { |b| b.name }
                            when 'year' then @active_breweries.sort_by { |b| b.year }
                          end
      @retired_breweries = case @order
                             when 'name' then @retired_breweries.sort_by { |b| b.name }
                             when 'year' then @retired_breweries.sort_by { |b| b.year }
                           end
    else
      @active_breweries = case @order
                            when 'name' then @active_breweries.sort_by { |b| b.name }.reverse
                            when 'year' then @active_breweries.sort_by { |b| b.year }.reverse
                          end
      @retired_breweries = case @order
                             when 'name' then @retired_breweries.sort_by { |b| b.name }.reverse
                             when 'year' then @retired_breweries.sort_by { |b| b.year }.reverse
                           end
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_all
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_all
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_all
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    expire_all
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  def expire_all
    ["brewerylist-name-asc", "brewerylist-name-desc", "brewerylist-year-asc", "brewerylist-year-desc"].each{ |f| expire_fragment(f) }
  end

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
    <% if @brewery.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

          <ul>
            <% @brewery.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.number_field :year %>
    </div>
    <div class="field">
      <%= f.label :active %>
      <%= f.check_box :active %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:'name', sort:@direction) %></th>
    <th><%= link_to 'Year', breweries_path(order:'year', sort:@direction) %></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<div style="border-style: solid;">
  brewerylist-name-asc: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-name-asc' ) %>
  <br>
  brewerylist-name-desc: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-name-desc' ) %>
  <br>
  brewerylist-year-asc: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-year-asc' ) %>
  <br>
  current: <%= "brewerylist-#{@order}-#{@direction}" %>
</div>

<% cache "brewerylist-#{@order}-#{@direction}", skip_digest: true do %>

    <p> Number of breweries: <%= @active_breweries.count + @retired_breweries.count %> </p>
    <h2>Active</h2>

    <p> Number of active breweries: <%= @active_breweries.count %> </p>

    <%= render 'list', breweries: @active_breweries %>

    <h2>Retired</h2>

    <p> Number of retired breweries: <%= @retired_breweries.count %> </p>

    <%= render 'list', breweries: @retired_breweries %>

    <br>
<% end %>

<%= link_to 'List of beers', beers_path, class:'btn btn-default'  %>
<%= link_to 'New Brewery', new_brewery_path, class:'btn btn-primary' if current_user %>

app/views/breweries/list.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js"></script>
<script>
    var myApp = angular.module('myApp', []);

    myApp.controller("BreweriesController", function ($scope, $http) {
        $http.get('breweries.json').success( function(data, status, headers, config) {
            $scope.breweries = data;
        });

        $scope.order = 'name';

        $scope.sort_by = function (order){
            $scope.order = order;
            console.log(order);
        }

        $scope.searchText = '';
    });
</script>

<h2>Beers</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">name</a> </th>
    <th> <a ng-click="sort_by('year')">year</a> </th>
    <th> <a ng-click="sort_by('beers.length')">beers</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
      <td>{{brewery.beers.length}}</td>
    </tr>
  </table>

</div>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<div style="border-style: solid;">
  current: <%= "#{@brewery.cache_key}" %>
</div>

<% cache @brewery do %>
    <p>
    <h2><%= @brewery.name %>
      <% if not @brewery.active  %>
          <span class="label label-info">retired</span>
      <% end %>
    </h2>
    </p>

    <p>
      <i>Established in <%= @brewery.year %></i>
    </p>
    <p>
      Number of beers <%= @brewery.beers.count %>
    </p>
    <p>
      <% @brewery.beers.each do |beer| %>
          <%= link_to beer.name, beer_path(beer.id) %>
      <% end %>
    </p>
    <p>
      <% if @brewery.ratings.empty? %>

      <% else %>
          Has <%= pluralize(@brewery.ratings.count, "rating") %>, average <%= @brewery.average_rating %>
      <% end %>
    </p>
    <p>
      <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
    </p>
<% end %>
<p>
  <%= link_to 'Back', breweries_path, class:'btn btn-default' %>
  <%= link_to 'Edit', edit_brewery_path(@brewery), class:'btn btn-primary' if current_user%>
</p>
<p>
  <%= link_to 'Destroy', @beer, class:'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } if current_user %>
</p>